targets = [ "//:sync" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-chrono"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-intrusive"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-system"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-thread"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "branch=master"
